In [1]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [26]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [27]:
df.shape

(10000, 14)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [30]:
df = df.drop(columns=['stab'])
df['stabf'] = np.where(df['stabf']=='unstable', 0, 1)
X = df.drop(columns=['stabf'])
y = df['stabf']

In [32]:
X.shape

(10000, 12)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [57]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [39]:
sc =  StandardScaler()
X_train_scaled = sc.fit_transform(X_train)

In [42]:
X_test_scaled = sc.transform(X_test)

In [43]:
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

RandomForestClassifier()

In [49]:
y_pred_rf = rf.predict(X_test_scaled)

In [50]:
accuracy_score(y_test, y_pred_rf)

0.9195

In [51]:
confusion_matrix(y_test, y_pred_rf)

array([[1227,   61],
       [ 100,  612]], dtype=int64)

In [48]:
extraTr = ExtraTreeClassifier()
extraTr.fit(X_train_scaled, y_train)

ExtraTreeClassifier()

In [52]:
y_pred_extr = extraTr.predict(X_test_scaled)

In [53]:
accuracy_score(y_test, y_pred_extr)

0.764

In [54]:
confusion_matrix(y_test, y_pred_extr)

array([[1035,  253],
       [ 219,  493]], dtype=int64)

In [59]:
xg = XGBClassifier()
xg.fit(X_train_scaled, y_train)

[23:43:51] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [62]:
y_pred_xg = xg.predict(X_test_scaled)

In [63]:
accuracy_xg = accuracy_score(y_test, y_pred_xg )

In [64]:
accuracy_xg

0.9455

In [65]:
confsion_xg = confusion_matrix(y_test, y_pred_xg)

In [66]:
confsion_xg

array([[1243,   45],
       [  64,  648]], dtype=int64)

In [67]:
lgbm = LGBMClassifier()

In [68]:
lgbm.fit(X_train_scaled, y_train)

LGBMClassifier()

In [75]:
y_pred_lgbm = lgbm.predict(X_test_scaled)

In [76]:
accuracy_lgbm = accuracy_score(y_test, y_pred_lgbm)

In [77]:
accuracy_lgbm

0.9395

In [78]:
confusion_lgbm = confusion_matrix(y_test, y_pred_lgbm)

In [79]:
confusion_lgbm

array([[1238,   50],
       [  71,  641]], dtype=int64)

In [80]:
extraTr.feature_importances_

array([0.12057943, 0.12619655, 0.11643259, 0.10689606, 0.04055359,
       0.03603442, 0.04105835, 0.0332657 , 0.08169417, 0.10273081,
       0.09119645, 0.10336186])

In [81]:
X.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4'],
      dtype='object')

In [82]:
from sklearn.model_selection import RandomizedSearchCV

In [96]:
param_distribution = {
    #'n_estimators': [100, 300, 500, 1000],
    'min_samples_leaf': [4, 6, 8],
    'min_samples_split': [2, 5, 7],
    'max_features': [None, 'auto', 'log2']
    
}

In [97]:
extr = ExtraTreeClassifier()

In [98]:
model_random_search = RandomizedSearchCV(extr, param_distributions=param_distribution, cv=5, n_iter=10, verbose=1, n_jobs=-1,
                                        scoring='accuracy', random_state=1)

In [99]:
model_random_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=ExtraTreeClassifier(), n_jobs=-1,
                   param_distributions={'max_features': [None, 'auto', 'log2'],
                                        'min_samples_leaf': [4, 6, 8],
                                        'min_samples_split': [2, 5, 7]},
                   random_state=1, scoring='accuracy', verbose=1)

In [100]:
model_random_search.best_params_

{'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': None}

In [102]:
y_pred_extr_rand = model_random_search.predict(X_test_scaled)

In [103]:
accuracy_score(y_pred_extr_rand, y_test)

0.841